/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    AiTranslator: typeof import('./src/components/AiTranslator.vue')['default']
    AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/common/AppSidebar.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DarkModeToggle: typeof import('./src/components/common/DarkModeToggle.vue')['default']
    DatabaseTest: typeof import('./src/components/DatabaseTest.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ProjectImport: typeof import('./src/components/project/ProjectImport.vue')['default']
    ProjectSelector: typeof import('./src/components/project/ProjectSelector.vue')['default']
    ProviderSettings: typeof import('./src/components/project/ProviderSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('primevue/slider')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ThemeSwitch: typeof import('./src/components/common/ThemeSwitch.vue')['default']
    TranslatedList: typeof import('./src/components/project/TranslatedList.vue')['default']
    TranslationList: typeof import('./src/components/project/TranslationList.vue')['default']
    TranslationProgress: typeof import('./src/components/project/TranslationProgress.vue')['default']
    TranslationSettings: typeof import('./src/components/project/TranslationSettings.vue')['default']
    TranslationTable: typeof import('./src/components/project/TranslationTable.vue')['default']
    Tree: typeof import('primevue/tree')['default']
    UntranslatedList: typeof import('./src/components/project/UntranslatedList.vue')['default']
  }
}
